Metrics/PerceivedComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 50
AllCops:
  Exclude:
    - '**/node_modules/**/*'
    - '**/vendor/**/*'
    - '**/bundle/**/*'
