Metrics/PerceivedComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 60
Metrics/AbcSize:
  Max: 60
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/BlockLength:
  Max: 50
Style/SymbolProc:
  # `Style/SymbolProc` can break when using `map` with `refine` in Ruby 2.4>
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  Exclude:
    - '**/node_modules/**/*'
    - '**/vendor/**/*'
    - '**/bundle/**/*'
