Metrics/PerceivedComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 60
Metrics/AbcSize:
  Max: 60
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/BlockLength:
  Max: 50
Style/SymbolProc:
  # Style/SymbolProc can break when using map with refine in Ruby 2.4>
  Enabled: false
Style/FrozenStringLiteralComment:
  # This rule doesn't work when run locally
  Enabled: false
Style/SafeNavigation:
  # This rule doesn't work when run locally
  Enabled: false
Style/NumericPredicate:
  # This rule doesn't work when run locally
  Enabled: false
AllCops:
  Exclude:
    - '**/node_modules/**/*'
    - '**/vendor/**/*'
    - '**/bundle/**/*'
Metrics/LineLength:
  Exclude:
    - 'test/tc_view.rb'
    - 'test/tc_escape.rb'
    - 'test/data/Data.replaplugin/Contents/Resources/data.rb'
    - 'test/tc_window.rb'
    - 'lib/repla/logger/test/tc_logger.rb'
    - 'lib/repla/test/packages/HelloWorld.replaplugin/Contents/Resources/hello_world.rb'
    - 'lib/repla/test/packages/Print.replaplugin/Contents/Resources/print.rb'
    - 'lib/repla/test/packages/TestEnvironment.replaplugin/Contents/Resources/test_environment.rb'
    - 'lib/repla/resources/js/bullets/test/run_tests.rb'
    - 'lib/repla/repl/test/tc_output_controller.rb'
    - 'lib/repla/repl/test/tc_repl.rb'
    - 'lib/repla/repl/test/tc_input_controller.rb'
    - 'lib/repla/dependencies/test/tc_dependencies.rb'
    - 'lib/repla/dependencies/test/tc_controller.rb'
    - 'lib/repla/dependencies/test/tc_tester.rb'
    - 'test/tc_module.rb'
    - 'test/tc_view_javascript.rb'
    - 'test/tc_test.rb'
    - 'test/tc_view_resources.rb'
