TEST_JAVASCRIPT_FUNCTION_WITHOUT_ARGUMENTS_NAME = "withoutArguments"
TEST_JAVASCRIPT_FUNCTION_WITHOUT_ARGUMENTS_RESULT = "test"

TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_NAME = "withArguments"
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_STRING_ARGUMENTS = ["one", "two"]
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_STRING_RESULT = "onetwo"
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_INTEGER_ARGUMENTS = [1, 2]
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_INTEGER_RESULT = 3
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_FLOAT_ARGUMENTS = [1.2, 2.1]
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_FLOAT_RESULT = 3.3