TEST_JAVASCRIPT_FUNCTION_WITHOUT_ARGUMENTS_NAME = 'withoutArguments'.freeze
TEST_JAVASCRIPT_FUNCTION_WITHOUT_ARGUMENTS_RESULT = 'test'.freeze

TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_NAME = 'withArguments'.freeze
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_STRING_ARGUMENTS = %w[one two].freeze
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_STRING_RESULT = 'onetwo'.freeze
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_INTEGER_ARGUMENTS = [1, 2].freeze
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_INTEGER_RESULT = 3
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_FLOAT_ARGUMENTS = [1.2, 2.1].freeze
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_FLOAT_RESULT = 3.3
