require 'shellwords'
require_relative '../../../../../../lib/repla/test'
require Repla::Test::HELPER_FILE
require Repla::Test::REPLA_FILE

task default: ['data:tests']

namespace :data do
  task tests: [:clean_up]

  task :test_controller do
    controller_tests_file = File.join(__dir__,
                                      'tc_controller.rb')
    ruby Shellwords.escape(controller_tests_file)
  end

  task test_data: [:test_controller] do
    data_tests_file = File.join(__dir__, 'tc_data.rb')
    ruby Shellwords.escape(data_tests_file)
  end

  task clean_up: [:test_data] do
  end
end
